# Generated by Django 5.1.3 on 2024-11-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_events_count', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project_db.events')),
                ('participation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUsers',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project_db.organizations')),
            ],
            options={
                'db_table': 'organization_users',
                'managed': False,
            },
        ),
    ]
